// pages/phase4.tsx
import React, { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import { supabase } from "../lib/supabaseClient";
import { MarketingDashboard } from "../components/MarketingDashboard";
import { generateMarketing } from "../lib/marketing/ai";
import { setPhaseCompleted } from "../lib/utils/phaseProgress";
import type { BusinessIdea, FounderProfile } from "../types/business";

type SavedSelection = {
  savedAt: string;
  founder: FounderProfile;
  idea: BusinessIdea;
  createdAt: string;
};

type SubscriptionState = {
  active: boolean;
  status: string | null;
  currentPeriodEnd: string | null;
};

const SELECTION_KEY = "ai-business-os:selected-idea";
const BUSINESS_NAME_KEY = "ai-business-os:business-name";

function readSelection(): SavedSelection | null {
  if (typeof window === "undefined") return null;
  try {
    const raw = window.localStorage.getItem(SELECTION_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw);
    if (!parsed?.founder || !parsed?.idea) return null;
    return parsed as SavedSelection;
  } catch {
    return null;
  }
}

function readBusinessNameFallback(selection: SavedSelection | null) {
  if (typeof window === "undefined") return selection?.idea?.name ?? "";
  const saved = window.localStorage.getItem(BUSINESS_NAME_KEY);
  if (saved && saved.trim()) return saved.trim();
  return selection?.idea?.name ?? "";
}

function cx(...parts: Array<string | false | null | undefined>) {
  return parts.filter(Boolean).join(" ");
}

function makeSvgDataUrl(opts: {
  title: string;
  subtitle: string;
  cta: string;
  brandName: string;
  size: "square" | "story";
}) {
  const w = opts.size === "story" ? 1080 : 1080;
  const h = opts.size === "story" ? 1920 : 1080;

  const safe = (s: string) =>
    (s || "")
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;");

  const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#4F46E5"/>
      <stop offset="50%" stop-color="#0EA5E9"/>
      <stop offset="100%" stop-color="#22C55E"/>
    </linearGradient>
    <filter id="shadow" x="-20%" y="-20%" width="140%" height="140%">
      <feDropShadow dx="0" dy="18" stdDeviation="18" flood-color="#000" flood-opacity="0.35"/>
    </filter>
  </defs>

  <rect width="100%" height="100%" fill="url(#bg)"/>
  <rect x="80" y="80" width="${w - 160}" height="${h - 160}" rx="48" fill="rgba(0,0,0,0.25)" filter="url(#shadow)"/>
  <rect x="110" y="110" width="${w - 220}" height="${h - 220}" rx="38" fill="rgba(0,0,0,0.22)" stroke="rgba(255,255,255,0.22)" />

  <text x="140" y="220" font-family="Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial" font-size="44" fill="rgba(255,255,255,0.82)" letter-spacing="1">
    ${safe(opts.brandName || "Business Forge AI")}
  </text>

  <text x="140" y="360" font-family="Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial" font-size="92" font-weight="800" fill="#ffffff">
    ${safe(opts.title).slice(0, 28)}
  </text>

  <text x="140" y="470" font-family="Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial" font-size="44" fill="rgba(255,255,255,0.9)">
    ${safe(opts.subtitle).slice(0, 60)}
  </text>

  <g>
    <rect x="140" y="${h - 320}" width="${w - 280}" height="120" rx="26" fill="rgba(255,255,255,0.14)" stroke="rgba(255,255,255,0.22)"/>
    <text x="180" y="${h - 244}" font-family="Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial" font-size="44" font-weight="800" fill="#ffffff">
      ${safe(opts.cta).slice(0, 40)}
    </text>
    <text x="180" y="${h - 205}" font-family="Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial" font-size="28" fill="rgba(255,255,255,0.85)">
      Tap to learn more →
    </text>
  </g>

  <text x="140" y="${h - 110}" font-family="Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial" font-size="28" fill="rgba(255,255,255,0.75)">
    Generated by AI Business OS
  </text>
</svg>`;

  const encoded = encodeURIComponent(svg)
    .replace(/'/g, "%27")
    .replace(/"/g, "%22");
  return `data:image/svg+xml;charset=utf-8,${encoded}`;
}

async function copyToClipboard(text: string) {
  try {
    await navigator.clipboard.writeText(text);
  } catch {
    // ignore
  }
}

export default function Phase4Page() {
  const router = useRouter();

  const [mounted, setMounted] = useState(false);
  const [session, setSession] = useState<any>(null);
  const [subscription, setSubscription] = useState<SubscriptionState>({
    active: false,
    status: null,
    currentPeriodEnd: null,
  });

  const [selection, setSelection] = useState<SavedSelection | null>(null);
  const [marketingData, setMarketingData] = useState<any>(null);

  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const businessName = useMemo(() => readBusinessNameFallback(selection), [selection]);
  const location = useMemo(() => selection?.founder?.location || "USA", [selection]);

  // mount + auth state
  useEffect(() => {
    setMounted(true);

    supabase.auth.getSession().then(({ data }) => setSession(data.session ?? null));
    const { data: listener } = supabase.auth.onAuthStateChange((_event, sess) => {
      setSession(sess ?? null);
    });

    return () => listener.subscription.unsubscribe();
  }, []);

  // selection
  useEffect(() => {
    setSelection(readSelection());
  }, []);

  // subscription state
  async function refreshMe() {
    try {
      const res = await fetch("/api/me");
      const json = await res.json();
      setSubscription(json?.subscription ?? { active: false, status: null, currentPeriodEnd: null });
    } catch {
      setSubscription({ active: false, status: null, currentPeriodEnd: null });
    }
  }

  useEffect(() => {
    if (!mounted) return;
    refreshMe();
    // refresh again shortly after auth change (cookie propagation)
    const t = setTimeout(() => refreshMe(), 500);
    return () => clearTimeout(t);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [mounted, session?.user?.id]);

  // gate: must be logged in + active subscription
  useEffect(() => {
    if (!mounted) return;

    if (!session) {
      const redirectedFrom = encodeURIComponent(router.asPath || "/phase4");
      router.replace(`/login?redirectedFrom=${redirectedFrom}`);
      return;
    }

    if (!subscription.active) {
      const from = encodeURIComponent(router.asPath || "/phase4");
      router.replace(`/pricing?from=${from}`);
      return;
    }
  }, [mounted, session, subscription.active, router]);

  async function handleGenerate() {
    if (!selection) return;

    setBusy(true);
    setError(null);
    try {
      const data = await generateMarketing({
        founder: selection.founder,
        businessName: businessName || selection.idea.name,
        location,
      });

      setMarketingData(data);

      setPhaseCompleted("phase1", true);
      setPhaseCompleted("phase4", true);
    } catch (e: any) {
      setError(e?.message || "Marketing generation failed.");
    } finally {
      setBusy(false);
    }
  }

  if (!mounted || !session || !subscription.active) {
    return (
      <div className="max-w-3xl mx-auto space-y-4">
        <h1 className="text-3xl font-bold">Phase 4 — Marketing</h1>
        <p className="text-white/60">Loading…</p>
      </div>
    );
  }

  if (!selection) {
    return (
      <div className="max-w-3xl mx-auto space-y-4">
        <h1 className="text-3xl font-bold">Phase 4 — Marketing</h1>
        <p className="text-white/70">To continue, select a business idea in Phase 1.</p>
        <div className="flex gap-3">
          <Link href="/phase1" className="px-4 py-2 rounded bg-blue-600 hover:bg-blue-700">
            Go to Phase 1
          </Link>
          <Link href="/phase3" className="px-4 py-2 rounded bg-gray-700 hover:bg-gray-600">
            Go to Phase 3
          </Link>
        </div>
      </div>
    );
  }

  // “premium creative” defaults (works even if marketingData format varies)
  const creativeTitle =
    marketingData?.headline ||
    marketingData?.adHeadline ||
    marketingData?.positioning?.headline ||
    `Grow ${businessName || selection.idea.name}`;

  const creativeSubtitle =
    marketingData?.subheadline ||
    marketingData?.tagline ||
    marketingData?.positioning?.tagline ||
    "A simple offer that converts — built for solo founders.";

  const creativeCta =
    marketingData?.cta ||
    marketingData?.primaryCta ||
    marketingData?.offer?.cta ||
    "Get started today";

  const squareUrl = makeSvgDataUrl({
    title: String(creativeTitle),
    subtitle: String(creativeSubtitle),
    cta: String(creativeCta),
    brandName: businessName || selection.idea.name,
    size: "square",
  });

  const storyUrl = makeSvgDataUrl({
    title: String(creativeTitle),
    subtitle: String(creativeSubtitle),
    cta: String(creativeCta),
    brandName: businessName || selection.idea.name,
    size: "story",
  });

  return (
    <div className="max-w-6xl mx-auto space-y-8">
      {/* Hero */}
      <div className="rounded-3xl border border-white/10 bg-gradient-to-br from-white/10 to-white/5 p-6 backdrop-blur">
        <div className="flex flex-col gap-2">
          <h1 className="text-3xl font-bold">Phase 4 — Marketing Engine</h1>
          <p className="text-white/70">
            Business: <span className="font-semibold text-white">{businessName || selection.idea.name}</span>
            <span className="text-white/40"> • </span>
            Location: <span className="font-semibold text-white">{location}</span>
          </p>
          <p className="text-sm text-white/60">
            You’ll get launch-ready copy + downloadable ad/post creatives you can use immediately.
          </p>
        </div>

        <div className="mt-5 flex flex-wrap gap-3">
          <button
            onClick={handleGenerate}
            disabled={busy}
            className={cx(
              "rounded-xl px-5 py-3 text-sm font-semibold transition",
              busy ? "bg-white/10 text-white/50" : "bg-indigo-600 hover:bg-indigo-500 text-white"
            )}
          >
            {busy ? "Generating…" : "Generate Marketing Kit"}
          </button>

          <Link
            href="/phase5"
            className="rounded-xl border border-white/15 bg-white/5 px-5 py-3 text-sm font-semibold text-white hover:bg-white/10"
          >
            Go to Phase 5 →
          </Link>

          <button
            onClick={() => refreshMe()}
            className="rounded-xl border border-white/15 bg-white/5 px-5 py-3 text-sm font-semibold text-white hover:bg-white/10"
          >
            Refresh subscription
          </button>
        </div>
      </div>

      {error && (
        <div className="rounded-2xl border border-red-500/25 bg-red-500/10 p-4 text-red-100">
          {error}
        </div>
      )}

      {/* Deliverables */}
      <div className="grid gap-6 lg:grid-cols-3">
        <div className="rounded-2xl border border-white/10 bg-white/5 p-5">
          <div className="text-xs uppercase tracking-wide text-white/50">Deliverable</div>
          <div className="mt-2 text-lg font-semibold">Social posts</div>
          <div className="mt-1 text-sm text-white/70">Launch-ready captions + hooks (copy/paste).</div>
        </div>

        <div className="rounded-2xl border border-white/10 bg-white/5 p-5">
          <div className="text-xs uppercase tracking-wide text-white/50">Deliverable</div>
          <div className="mt-2 text-lg font-semibold">Ad copy</div>
          <div className="mt-1 text-sm text-white/70">Headlines + primary text + CTA variations.</div>
        </div>

        <div className="rounded-2xl border border-white/10 bg-white/5 p-5">
          <div className="text-xs uppercase tracking-wide text-white/50">Deliverable</div>
          <div className="mt-2 text-lg font-semibold">Creative images</div>
          <div className="mt-1 text-sm text-white/70">
            Downloadable square + story creative (SVG). Works everywhere.
          </div>
        </div>
      </div>

      {/* Creative Preview + Download */}
      <div className="rounded-3xl border border-white/10 bg-white/5 p-6">
        <div className="flex flex-col gap-2 md:flex-row md:items-end md:justify-between">
          <div>
            <h2 className="text-xl font-semibold">Instant creative assets</h2>
            <p className="text-sm text-white/60">
              These update after generation, but also look good even before you generate.
            </p>
          </div>

          <div className="flex flex-wrap gap-3">
            <a
              href={squareUrl}
              download="ad-creative-square.svg"
              className="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-500"
            >
              Download square
            </a>
            <a
              href={storyUrl}
              download="ad-creative-story.svg"
              className="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-500"
            >
              Download story
            </a>
            <button
              onClick={() =>
                copyToClipboard(
                  `Headline: ${creativeTitle}\nSub: ${creativeSubtitle}\nCTA: ${creativeCta}\nBusiness: ${businessName || selection.idea.name}`
                )
              }
              className="rounded-xl border border-white/15 bg-white/5 px-4 py-2 text-sm font-semibold text-white hover:bg-white/10"
            >
              Copy creative text
            </button>
          </div>
        </div>

        <div className="mt-6 grid gap-6 lg:grid-cols-2">
          <div className="rounded-2xl border border-white/10 bg-black/20 p-4">
            <div className="text-sm font-semibold text-white/90">Square (1:1)</div>
            <div className="mt-3 overflow-hidden rounded-xl border border-white/10 bg-black/30">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src={squareUrl} alt="Square creative" className="w-full h-auto" />
            </div>
          </div>

          <div className="rounded-2xl border border-white/10 bg-black/20 p-4">
            <div className="text-sm font-semibold text-white/90">Story (9:16)</div>
            <div className="mt-3 overflow-hidden rounded-xl border border-white/10 bg-black/30">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src={storyUrl} alt="Story creative" className="w-full h-auto" />
            </div>
          </div>
        </div>
      </div>

      {/* Existing dashboard output (your current component) */}
      {marketingData && (
        <div className="rounded-3xl border border-white/10 bg-white/5 p-6">
          <div className="flex items-end justify-between gap-3">
            <div>
              <h2 className="text-xl font-semibold">Your marketing kit</h2>
              <p className="text-sm text-white/60">Generated strategy + copy outputs.</p>
            </div>
          </div>

          <div className="mt-5">
            <MarketingDashboard marketingData={marketingData} />
          </div>
        </div>
      )}
    </div>
  );
}
